# Generated by Django 6.0 on 2026-04-09 14:05

import my_portal.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portal', '0003_rename_is_current_working_experience_is_currently_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='certificate_link',
            field=models.URLField(blank=True, null=True, validators=[my_portal.validator.validate_safe_url]),
        ),
    ]
