# Generated by Django 6.0 on 2026-04-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portal', '0004_alter_certificates_certificate_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='course_duration',
            field=models.DurationField(),
        ),
    ]
