# Generated by Django 6.0 on 2026-04-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portal', '0005_alter_certificates_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='course_duration',
            field=models.PositiveIntegerField(),
        ),
    ]
